// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlbWhlhwIIm1uTIyjaBbjpO_759GxFWhs',
    appId: '1:869775285536:web:7340c52f3b0deb869acb45',
    messagingSenderId: '869775285536',
    projectId: 'zipit-7b897',
    authDomain: 'zipit-7b897.firebaseapp.com',
    storageBucket: 'zipit-7b897.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTUH0YATXtyYiGTq0aGDTWS4-IqALb1IY',
    appId: '1:869775285536:android:8d9c29781f800a279acb45',
    messagingSenderId: '869775285536',
    projectId: 'zipit-7b897',
    storageBucket: 'zipit-7b897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQS8Rxq_4KdQ8rGD9b8N2kh8AwX3PJCEA',
    appId: '1:869775285536:ios:179e90437561e1ee9acb45',
    messagingSenderId: '869775285536',
    projectId: 'zipit-7b897',
    storageBucket: 'zipit-7b897.appspot.com',
    iosClientId: '869775285536-dgiap7nu47igdljldpmst332jndb3sun.apps.googleusercontent.com',
    iosBundleId: 'com.example.zipit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQS8Rxq_4KdQ8rGD9b8N2kh8AwX3PJCEA',
    appId: '1:869775285536:ios:179e90437561e1ee9acb45',
    messagingSenderId: '869775285536',
    projectId: 'zipit-7b897',
    storageBucket: 'zipit-7b897.appspot.com',
    iosClientId: '869775285536-dgiap7nu47igdljldpmst332jndb3sun.apps.googleusercontent.com',
    iosBundleId: 'com.example.zipit',
  );
}
